

DROP TABLE IF EXISTS `melange`;
CREATE TABLE IF NOT EXISTS `melange` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `nom_melange` varchar(256) NOT NULL,
  `nom_user` varchar(256) NOT NULL,
  `date_melange` date NOT NULL,
  `nom_produit` varchar(256) NOT NULL,
  `concentration_melange` varchar(256) NOT NULL,
  `milieu` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
